### ISSUE TITLE
Point

### ISSUE THREAD

**Issue by manupuchades** [manupuchades/IWVG.SwC.ManuPuchades#2]
[Ver wiki](https://github.com/manupuchades/IWVG.SwC.ManuPuchades/wiki#point)

**Comment by ATorreclla** [comment]
He pasado los test de issue#2 de forma correcta. Doy por terminada la issue. 
Se realiza merge con la rama develop.

**Comment by manupuchades** [comment]
Hola Agustín, como te comenté voy a tener que hacer un revert de algunos commits.

Por desgracia tus cambios se verán afectados, asi que voy a reabir la tarea. En cuanto estén corregidos los problemas en develop habrá que volver a subir el código. Aprovecho para decirte que estaba perfecto 👍 

Entiendo que es una carga inesperada, asi que si ves que no vas a tener tiempo por favor avisame.

Un saludo

**Comment by manupuchades** [comment]
Hola, ya está de nuevo dispoible el códido. 

Puedes retomar la tarea cuando tengas tiempo. No dudes en consultarme para cualquier cosa.

Muchas gracias.

**Comment by ATorreclla** [comment]
Se solucionan los problemas y se sube con merge a develop. En funcionamiento correcto.
