### ISSUE TITLE
Decimal Collection

### ISSUE THREAD

**Issue by manupuchades** [manupuchades/IWVG.SwC.ManuPuchades#4]
[Ver wiki](https://github.com/manupuchades/IWVG.SwC.ManuPuchades/wiki#decimal-collection)

**Comment by manupuchades** [comment]
Voy a reabrir la tarea.
El lunes por la noche limpiaré develop y lo dejaré como estaba hasta el último commit de Daniel Peréz.

A partir de ahí habrá que retomar la tarea. 

Fijate bien que lo que se ha pedido es hacer un metodo set(). Voy a dejarlo mas detallado en la wiki.. Si tienes dudas puedes preguntarme cuando quieras, tambien puedes mirar lo que ha subido Daniel Perez en la clase User.

Voy a estudiar como hacer para que no se suban todos los archivos de configuración de intellij, vamos a tener que tener cuidado con eso para que no vuelva a ocurrir.

Desplazo también la fecha de entrega al jueves noche para que tengas tiempo. Si por lo que sea ves que no vas a poder realizar la tarea, te pido por favor que me avises cuanto antes.

Un saludo.

**Comment by RealityMistic** [comment]
Hola Manu

corregiré el método tan pronto como lo subas o a más tardar el martes.

Respecto a la forma de quitar los ficheros de configuración del git, basta con crear un archivo .gitignore en la rama develop de la cual yo haré un pull para empezar a trabajar de nuevo
Contenido de .gitignore


.idea
*.iws
*.iml
*.ipr

target

**Comment by manupuchades** [comment]
Muchas gracias! en cuanto el código vuelva a estar disponible te aviso.

**Comment by manupuchades** [comment]
Hola, ya está de nuevo dispoible el códido. 

He realizado un revert hasta la versión estable y he incluido el gitIgnore para mantener limpio el código.

Puedes retomar la tarea cuando tengas tiempo. No dudes en consultarme para cualquier cosa.

Muchas gracias.

**Comment by manupuchades** [comment]
He vuelto a resetear develop. Avisame si tienes problemas
