### ISSUE TITLE
Fraction : set

### ISSUE THREAD

**Issue by manupuchades** [manupuchades/IWVG.SwC.ManuPuchades#5]
[Ver wiki](https://github.com/manupuchades/IWVG.SwC.ManuPuchades/wiki#funcionalidad-set)

**Comment by ATorreclla** [comment]
He realizado la issue#5. He pasado de forma correcta los test.
Se realiza merge sobre la rama develop, Sin errores.

**Comment by manupuchades** [comment]
Hola Agustín, como te comenté voy a tener que hacer un revert de algunos commits.

Por desgracia tus cambios se verán afectados, asi que voy a reabir la tarea. En cuanto estén corregidos los problemas en develop habrá que volver a subir el código. Aprovecho para decirte que estaba perfecto 👍 

Entiendo que es una carga inesperada, asi que si ves que no vas a tener tiempo por favor avisame.

Un saludo

**Comment by manupuchades** [comment]
Hola, ya está de nuevo dispoible el códido. 

Puedes retomar la tarea cuando tengas tiempo. No dudes en consultarme para cualquier cosa.

Recuerda comprobar que tu código esté actualizado cuando vayas a subirlo para evitar conflictos con tu compañero César.

Muchas gracias.

**Comment by ATorreclla** [comment]
Se solucionan los problemas habidos. Se pasan los test de forma correcta y se lleva con merge a develop.
