### ISSUE TITLE
Fraction : divide

### ISSUE THREAD

**Issue by manupuchades** [manupuchades/IWVG.SwC.ManuPuchades#7]
[Ver wiki](https://github.com/manupuchades/IWVG.SwC.ManuPuchades/wiki#funcionalidad-divide)

**Comment by manupuchades** [comment]
Reabro esta tarea.

Habrá que retormar la tarea una vez arreglado el problema en develop.

El código está genial, sin embargo, cuando vayas a hacer commit fijate que haces commits diferentes (con diferentes descripciones) de cada issue. Así resultará mas fácil localizar las mejoras en las que has trabajado.

**Comment by RealityMistic** [comment]
Sí, ha sido un error el mezclar ambas modificaciones en un mismo commit, es porque todavía no me manejaba muy bien con git, pero a la próxima espero hacerlo bien

Gracias

**Comment by manupuchades** [comment]
Hola, ya está de nuevo dispoible el códido. 

Puedes retomar la tarea cuando tengas tiempo. No dudes en consultarme para cualquier cosa.

Recuerda comprobar que tu código esté actualizado cuando vayas a subirlo para evitar conflictos con tu compañero Agustin.

Muchas gracias.
